sim:
  a: 0
  b: 1.0
  Nx: 128  # dx = (b-a)/Nx
  s: 0
  t: 0.5
  Nt: 50  # dt = (t-s)/Nt = 1e-2
  noise_type: Q  # ${noise_type}  # either 'cyl' or 'Q'
  truncation: 128  # sim.truncation=32,64,128,256
  sigma: 0.5  # coefficient of additive diffusive term
  fix_u0: True  # True -> fix; False -> vary
  num: 1200

seed: 42

save_dir: '../results/KdV+/'
save_name: 'KdV+'