sim:
  a: 0
  b: 1.0
  Nx: 128  # dx = (b-a)/Nx
  s: 0
  t: 0.05
  Nt: 50  # dt = (t-s)/Nt
  truncation: 128  # [32,64,128,256]
  sigma: 0.1  # coefficient of additive diffusive term
  fix_u0: True  # [True,False] True--fix; False--vary
  num: 1200

seed: 42

save_dir: '../results/Phi41+/'
save_name: 'Phi41+'