sim:
  a: 0
  b: 1.0
  Nx: 128
  s: 0
  t: 0.5
  Nt: 500
  truncation: 128  # [32,64,128,256]
  fix_u0: True  # [True,False] True--fix; False--vary
  num: 1200

seed: 42

save_dir: '../results/wave/'
save_name: 'wave'
