model: FNO
equation: Phi41+
data: Phi41+sigma01_xi_trc128_1200

data_path: '../../data_gen/results/${equation}/${data}.mat'
dim_x: 128
T: 51
sub_t: 1

width: 32  # grid search: [32]
L: 3 # grid search: [1, 2, 3, 4]
# Used in SPDEBench: Phi41+sigma01:3, Phi41+sigma1:1, KdV+Q:1, KdV+cyl:1, wave:4
modes1: 32  # grid search: [16, 32]
# Used in SPDEBench: Phi41+sigma01:32, Phi41+sigma1:32, KdV+Q:16, KdV+cyl:16, wave:32
modes2: 25  # grid search: [16, 25]
# Used in SPDEBench: Phi41+sigma01:25, Phi41+sigma1:25, KdV+Q:16, KdV+cyl:25, wave:25

ntrain: 840
nval: 180
ntest: 180
batch_size: 20
epochs: 1000
learning_rate: 0.0025
weight_decay: 1e-4
#scheduler_step: 100
#scheduler_gamma: 0.5
plateau_patience: 50
delta: 0.0001
plateau_terminate: 100

print_every: 100

seed: 3407

save_dir: '../result/${model}_${equation}/'
checkpoint_file: '${data}.pth'

log_file: '${data}_log'