model: FNO
equation: NS
data: NS_xi_trc128

data_path: '../../data_gen/results/${data}/merged_ns_1200.mat'
sub_x: 1
T: 100
sub_t: 1

L: 4  # grid search: [3, 4]
# Used in SPDEBench: NS:3
modes1: 8  # grid search: [8, 16]
# Used in SPDEBench: NS:8
modes2: 8
modes3: 8
width: 32  # grid search: [32]

ntrain: 840
nval: 180
ntest: 180
batch_size: 20
epochs: 1000
learning_rate: 0.001  #[0.0075, 0.005, 0.0025, 0.001]
plateau_patience: 50
delta: 0.0001
plateau_terminate: 100

print_every: 20

seed: 3407

save_dir: '../result/${model}_${equation}/'
checkpoint_file: '${data}.pth'

log_file: '${data}_log'
