model: NSPDE
equation: Phi41+
data: Phi41+sigma01_xi_trc128_1200

data_path: '../../data_gen/results/${equation}/${data}.mat'
dim_x: 128
T: 51
sub_t: 1

hidden_channels: 32   # grid search: [32]
n_iter: 1   # grid search: [1, 2, 3, 4]
# Used in SPDEBench: Phi41+sigma01:1, Phi41+sigma1:1, KdV+Q:3, KdV+cyl:2, wave:4
modes1: 64   # grid search: [32, 64]
# Used in SPDEBench: Phi41+sigma01:64, Phi41+sigma1:64, KdV+Q:32, KdV+cyl:32, wave:64
modes2: 50   # grid search: [32, 50]
# Used in SPDEBench: Phi41+sigma01:50, Phi41+sigma1:50, KdV+Q:50, KdV+cyl:32, wave:32

ntrain: 840
nval: 180
ntest: 180
batch_size: 20
epochs: 1000
learning_rate: 0.0025
weight_decay: 1e-4
#scheduler_step: 100
#scheduler_gamma: 0.5
plateau_patience: 50
delta: 0.0002
plateau_terminate: 100

print_every: 10

seed: 3407

save_dir: '../result/${model}_${equation}/'
checkpoint_file: '${data}.pth'

log_file: '${data}_log'